// keywords.ts
type KeywordConfig = {
  keywords: string[];
  wordsBeforeMap?: Record<string, number>;
  wordsAfterMap?: Record<string, number>;
};

const englishKeywordsConfig: KeywordConfig = {
  keywords: [
    'welcome to',
    'about',
    'store name',
    'our shop',
    'company',
    'brands',
    'our brands',
    'featured brands',
    'brand list',
    'designers',
    'collections',
    'products by brand',
    'opening hours',
    'store hours',
    'our hours',
    'business hours',
    'open',
    'closed',
    'monday',
    'tuesday',
    'wednesday',
    'thursday',
    'friday',
    'saturday',
    'sunday',
    'mon',
    'tue',
    'wed',
    'thu',
    'fri',
    'sat',
    'sun',
    'weekdays',
    'weekends',
    'public holidays',
    'from',
    'to',
    'and',
    'appointments',
    'address',
    'location',
    'find us',
    'visit us',
    'directions',
    'contact',
    'street',
    'avenue',
    'road',
    'lane',
    'place',
    'suite',
    'apt',
    'unit',
    'city',
    'state',
    'province',
    'zip code',
    'postal code',
    'country',
    'about us',
    'our story',
    'company profile',
    'who we are',
    'our mission',
    'our vision',
    'history',
    'return policy',
    'returns',
    'refunds',
    'exchanges',
    'shipping & returns',
    'customer service',
    'warranty',
    'guarantee',
    'terms and conditions',
    'how to return',
    'eligibility',
    'process',
    'categories',
    'shop by',
    'departments',
    'products',
    'what we sell',
    'services',
    'specialties',
    'electronics',
    'fashion',
    'clothing',
    'apparel',
    'footwear',
    'jewelry',
    'home goods',
    'furniture',
    'decor',
    'groceries',
    'food',
    'books',
    'sporting goods',
    'outdoor',
    'hardware',
    'tools',
    'pharmacy',
    'beauty',
    'cosmetics',
    'automotive',
    'kids',
    'toys',
    'pet supplies',
    'gifts',
    'art',
    'crafts',
    'music',
    'movies',
    'video games',
    'health',
    'wellness',
  ],
  wordsBeforeMap: {
    'opening hours': 10,
    'store hours': 10,
    'our hours': 10,
    'business hours': 10, // Narrow context for hour phrases
    open: 5,
    closed: 5, // Even narrower for specific day open/closed states
    monday: 5,
    tuesday: 5,
    wednesday: 5,
    thursday: 5,
    friday: 5,
    saturday: 5,
    sunday: 5,
    mon: 5,
    tue: 5,
    wed: 5,
    thu: 5,
    fri: 5,
    sat: 5,
    sun: 5,
    address: 15,
    location: 15,
    contact: 15, // Context around address details
    'about us': 20,
    'our story': 20,
    'company profile': 20, // Context around about sections
    'return policy': 20,
    returns: 20,
    refunds: 20, // Context around return policy details
    brands: 15,
    'our brands': 15,
    'featured brands': 15,
    'brand list': 15, // Context for brands
  },
  wordsAfterMap: {
    'opening hours': 150,
    'store hours': 150,
    'our hours': 150,
    'business hours': 150, // Large context to capture all daily hours
    open: 20,
    closed: 20, // To get the specific times or reason for closure
    monday: 30,
    tuesday: 30,
    wednesday: 30,
    thursday: 30,
    friday: 30,
    saturday: 30,
    sunday: 30,
    mon: 30,
    tue: 30,
    wed: 30,
    thu: 30,
    fri: 30,
    sat: 30,
    sun: 30,
    address: 50,
    location: 50,
    contact: 50, // To capture the full address
    'about us': 300,
    'our story': 300,
    'company profile': 300, // Large context for full 'about' text
    'return policy': 400,
    returns: 400,
    refunds: 400, // Very large context for detailed return policies
    brands: 100,
    'our brands': 100,
    'featured brands': 100,
    'brand list': 100, // Enough context to capture brand names
  },
};

const frenchKeywordsConfig: KeywordConfig = {
  keywords: [
    'bienvenue à',
    'à propos',
    'nom du magasin',
    'notre boutique',
    'entreprise',
    'marques',
    'nos marques',
    'marques vedettes',
    'liste des marques',
    'designers',
    'collections',
    'produits par marque',
    "heures d'ouverture",
    'horaires du magasin',
    'nos horaires',
    'heures de bureau',
    'ouvert',
    'fermé',
    'lundi',
    'mardi',
    'mercredi',
    'jeudi',
    'vendredi',
    'samedi',
    'dimanche',
    'lun',
    'mar',
    'mer',
    'jeu',
    'ven',
    'sam',
    'dim',
    'jours de semaine',
    'week-ends',
    'jours fériés',
    'de',
    'à',
    'et',
    'rendez-vous',
    'adresse',
    'emplacement',
    'nous trouver',
    'visitez-nous',
    'directions',
    'contact',
    'rue',
    'avenue',
    'route',
    'allée',
    'place',
    'suite',
    'apt',
    'unité',
    'ville',
    'état',
    'province',
    'code postal',
    'pays',
    'à propos de nous',
    'notre histoire',
    "profil d'entreprise",
    'qui sommes-nous',
    'notre mission',
    'notre vision',
    'histoire',
    'politique de retour',
    'retours',
    'remboursements',
    'échanges',
    'expédition & retours',
    'service client',
    'garantie',
    'conditions générales',
    'comment retourner',
    'éligibilité',
    'processus',
    'catégories',
    'acheter par',
    'départements',
    'produits',
    'ce que nous vendons',
    'services',
    'spécialités',
    'électronique',
    'mode',
    'vêtements',
    'habillement',
    'chaussures',
    'bijoux',
    'articles ménagers',
    'meubles',
    'décoration',
    'épicerie',
    'alimentation',
    'livres',
    'articles de sport',
    'plein air',
    'quincaillerie',
    'outils',
    'pharmacie',
    'beauté',
    'cosmétiques',
    'automobile',
    'enfants',
    'jouets',
    'articles pour animaux',
    'cadeaux',
    'art',
    'artisanat',
    'musique',
    'films',
    'jeux vidéo',
    'santé',
    'bien-être',
  ],
  wordsBeforeMap: {
    "heures d'ouverture": 10,
    'horaires du magasin': 10,
    'nos horaires': 10,
    'heures de bureau': 10,
    ouvert: 5,
    fermé: 5,
    lundi: 5,
    mardi: 5,
    mercredi: 5,
    jeudi: 5,
    vendredi: 5,
    samedi: 5,
    dimanche: 5,
    lun: 5,
    mar: 5,
    mer: 5,
    jeu: 5,
    ven: 5,
    sam: 5,
    dim: 5,
    adresse: 15,
    emplacement: 15,
    contact: 15,
    'à propos de nous': 20,
    'notre histoire': 20,
    "profil d'entreprise": 20,
    'politique de retour': 20,
    retours: 20,
    remboursements: 20,
    marques: 15,
    'nos marques': 15,
    'marques vedettes': 15,
    'liste des marques': 15,
  },
  wordsAfterMap: {
    "heures d'ouverture": 150,
    'horaires du magasin': 150,
    'nos horaires': 150,
    'heures de bureau': 150,
    ouvert: 20,
    fermé: 20,
    lundi: 30,
    mardi: 30,
    mercredi: 30,
    jeudi: 30,
    vendredi: 30,
    samedi: 30,
    dimanche: 30,
    lun: 30,
    mar: 30,
    mer: 30,
    jeu: 30,
    ven: 30,
    sam: 30,
    dim: 30,
    adresse: 50,
    emplacement: 50,
    contact: 50,
    'à propos de nous': 300,
    'notre histoire': 300,
    "profil d'entreprise": 300,
    'politique de retour': 400,
    retours: 400,
    remboursements: 400,
    marques: 100,
    'nos marques': 100,
    'marques vedettes': 100,
    'liste des marques': 100,
  },
};

const germanKeywordsConfig: KeywordConfig = {
  keywords: [
    'willkommen bei',
    'über',
    'geschäftsname',
    'unser laden',
    'unternehmen',
    'marken',
    'unsere marken',
    'ausgewählte marken',
    'markenliste',
    'designer',
    'kollektionen',
    'produkte nach marke',
    'öffnungszeiten',
    'geschäftszeiten',
    'unsere öffnungszeiten',
    'geschäftszeiten',
    'geöffnet',
    'geschlossen',
    'montag',
    'dienstag',
    'mittwoch',
    'donnerstag',
    'freitag',
    'samstag',
    'sonntag',
    'mo',
    'di',
    'mi',
    'do',
    'fr',
    'sa',
    'so',
    'werktags',
    'wochenenden',
    'feiertage',
    'von',
    'bis',
    'und',
    'termine',
    'adresse',
    'standort',
    'finden sie uns',
    'besuchen sie uns',
    'wegbeschreibung',
    'kontakt',
    'straße',
    'allee',
    'weg',
    'gasse',
    'platz',
    'suite',
    'apt',
    'einheit',
    'stadt',
    'bundesland',
    'provinz',
    'postleitzahl',
    'land',
    'über uns',
    'unsere geschichte',
    'firmenprofil',
    'wer wir sind',
    'unsere mission',
    'unsere vision',
    'geschichte',
    'rückgaberecht',
    'rücksendungen',
    'erstattungen',
    'umtausch',
    'versand & rückgabe',
    'kundenservice',
    'garantie',
    'allgemeine geschäftsbedingungen',
    'wie zurückgeben',
    'berechtigung',
    'prozess',
    'kategorien',
    'einkaufen nach',
    'abteilungen',
    'produkte',
    'was wir verkaufen',
    'dienstleistungen',
    'spezialitäten',
    'elektronik',
    'mode',
    'kleidung',
    'bekleidung',
    'schuhe',
    'schmuck',
    'haushaltswaren',
    'möbel',
    'dekoration',
    'lebensmittel',
    'essen',
    'bücher',
    'sportartikel',
    'outdoor',
    'hardware',
    'werkzeuge',
    'apotheke',
    'schönheit',
    'kosmetik',
    'automobil',
    'kinder',
    'spielzeug',
    'haustierbedarf',
    'geschenke',
    'kunst',
    'handwerk',
    'musik',
    'filme',
    'videospiele',
    'gesundheit',
    'wellness',
  ],
  wordsBeforeMap: {
    öffnungszeiten: 10,
    geschäftszeiten: 10,
    'unsere öffnungszeiten': 10,
    geöffnet: 5,
    geschlossen: 5,
    montag: 5,
    dienstag: 5,
    mittwoch: 5,
    donnerstag: 5,
    freitag: 5,
    samstag: 5,
    sonntag: 5,
    mo: 5,
    di: 5,
    mi: 5,
    do: 5,
    fr: 5,
    sa: 5,
    so: 5,
    adresse: 15,
    standort: 15,
    kontakt: 15,
    'über uns': 20,
    'unsere geschichte': 20,
    firmenprofil: 20,
    rückgaberecht: 20,
    rücksendungen: 20,
    erstattungen: 20,
    marken: 15,
    'unsere marken': 15,
    'ausgewählte marken': 15,
    markenliste: 15,
  },
  wordsAfterMap: {
    öffnungszeiten: 150,
    geschäftszeiten: 150,
    'unsere öffnungszeiten': 150,
    geöffnet: 20,
    geschlossen: 20,
    montag: 30,
    dienstag: 30,
    mittwoch: 30,
    donnerstag: 30,
    freitag: 30,
    samstag: 30,
    sonntag: 30,
    mo: 30,
    di: 30,
    mi: 30,
    do: 30,
    fr: 30,
    sa: 30,
    so: 30,
    adresse: 50,
    standort: 50,
    kontakt: 50,
    'über uns': 300,
    'unsere geschichte': 300,
    firmenprofil: 300,
    rückgaberecht: 400,
    rücksendungen: 400,
    erstattungen: 400,
    marken: 100,
    'unsere marken': 100,
    'ausgewählte marken': 100,
    markenliste: 100,
  },
};

const dutchKeywordsConfig: KeywordConfig = {
  keywords: [
    'welkom bij',
    'over',
    'winkelnaam',
    'onze winkel',
    'bedrijf',
    'merken',
    'onze merken',
    'uitgelichte merken',
    'merkenlijst',
    'ontwerpers',
    'collecties',
    'producten per merk',
    'openingstijden',
    'winkeltijden',
    'onze tijden',
    'kantooruren',
    'open',
    'gesloten',
    'maandag',
    'dinsdag',
    'woensdag',
    'donderdag',
    'vrijdag',
    'zaterdag',
    'zondag',
    'ma',
    'di',
    'wo',
    'do',
    'vr',
    'za',
    'zo',
    'doordeweeks',
    'weekenden',
    'feestdagen',
    'van',
    'tot',
    'en',
    'afspraken',
    'adres',
    'locatie',
    'vind ons',
    'bezoek ons',
    'routebeschrijving',
    'contact',
    'straat',
    'laan',
    'weg',
    'steeg',
    'plein',
    'suite',
    'apt',
    'unit',
    'stad',
    'staat',
    'provincie',
    'postcode',
    'land',
    'over ons',
    'ons verhaal',
    'bedrijfsprofiel',
    'wie we zijn',
    'onze missie',
    'onze visie',
    'geschiedenis',
    'retourbeleid',
    'retouren',
    'terugbetalingen',
    'ruilingen',
    'verzending & retour',
    'klantenservice',
    'garantie',
    'algemene voorwaarden',
    'hoe te retourneren',
    'in aanmerking komen',
    'proces',
    'categorieën',
    'winkelen op',
    'afdelingen',
    'producten',
    'wat we verkopen',
    'diensten',
    'specialiteiten',
    'elektronica',
    'mode',
    'kleding',
    'kleding',
    'schoenen',
    'sieraden',
    'huishoudelijke artikelen',
    'meubels',
    'decoratie',
    'boodschappen',
    'voeding',
    'boeken',
    'sportartikelen',
    'buitenleven',
    'hardware',
    'gereedschap',
    'apotheek',
    'schoonheid',
    'cosmetica',
    'automotive',
    'kinderen',
    'speelgoed',
    'dierenbenodigdheden',
    'cadeaus',
    'kunst',
    'handwerk',
    'muziek',
    'films',
    'videospellen',
    'gezondheid',
    'welzijn',
  ],
  wordsBeforeMap: {
    openingstijden: 10,
    winkeltijden: 10,
    'onze tijden': 10,
    kantooruren: 10,
    open: 5,
    gesloten: 5,
    maandag: 5,
    dinsdag: 5,
    woensdag: 5,
    donderdag: 5,
    vrijdag: 5,
    zaterdag: 5,
    zondag: 5,
    ma: 5,
    di: 5,
    wo: 5,
    do: 5,
    vr: 5,
    za: 5,
    zo: 5,
    adres: 15,
    locatie: 15,
    contact: 15,
    'over ons': 20,
    'ons verhaal': 20,
    bedrijfsprofiel: 20,
    retourbeleid: 20,
    retouren: 20,
    terugbetalingen: 20,
    merken: 15,
    'onze merken': 15,
    'uitgelichte merken': 15,
    merkenlijst: 15,
  },
  wordsAfterMap: {
    openingstijden: 150,
    winkeltijden: 150,
    'onze tijden': 150,
    kantooruren: 150,
    open: 20,
    gesloten: 20,
    maandag: 30,
    dinsdag: 30,
    woensdag: 30,
    donderdag: 30,
    vrijdag: 30,
    zaterdag: 30,
    zondag: 30,
    ma: 30,
    di: 30,
    wo: 30,
    do: 30,
    vr: 30,
    za: 30,
    zo: 30,
    adres: 50,
    locatie: 50,
    contact: 50,
    'over ons': 300,
    'ons verhaal': 300,
    bedrijfsprofiel: 300,
    retourbeleid: 400,
    retouren: 400,
    terugbetalingen: 400,
    merken: 100,
    'onze merken': 100,
    'uitgelichte merken': 100,
    merkenlijst: 100,
  },
};

const allKeywordsConfig: Record<string, KeywordConfig> = {
  en: englishKeywordsConfig,
  fr: frenchKeywordsConfig,
  de: germanKeywordsConfig, // Assuming you will fill this with detailed maps
  nl: dutchKeywordsConfig,
};

export default function getKeywords(language: string): KeywordConfig {
  // Use the specific language config or fall back to English
  return allKeywordsConfig[language] || allKeywordsConfig['en'];
}
