const excludeKeywords = [
  'heren',
  'dames',
  'ladies',
  'mannen',
  'man',
  'vrouw',
  'men',
  'kids',
  'kinderen',
  'kind',
  'baby',
  'babies',
  'meisjes',
  'jongens',
  'jong',
  'jongen',
  'jongedame',
  'jongeman',
  'jongvolwassenen',
  'volwassenen',
  'volwassene',
  'kinderkleding',
  'babykleding',
  "baby's",
  "baby's kleding",
  "baby's kleding",
  "baby's kleren",
  "baby's kledij",
  "baby's mode",
  "baby's outfits",
  "baby's kledingstukken",
  "baby's kledingcollectie",
  "baby's kledinglijn",
  "baby's kledingmerk",
  "baby's kledingwinkel",
  "baby's kledingzaak",
  "baby's kledingboetiek",
  "baby's kledingaccessoires",
  'bad',
  'kamperen',
  'kamperen',
  'kampeer',
  'kampeerartikelen',
  'kampeeraccessoires',
  'kampeerspullen',
  'kampeeruitrusting',
  'kampeerbenodigdheden',
  'kampeermateriaal',
  'kampeerkleding',
  'kampeermeubels',
  'kampeertenten',
  'kampeerstoelen',
  'kampeertafels',
  'kampeerlampen',
  'kampeerkookgerei',
  'kampeerkooktoestellen',
  'kampeerkookaccessoires',
  'producten',
  'producten',
  'product',
  'artikelen',
  'artikel',
  'spullen',
  'spul',
  'kleding',
  'kleren',
  'mode',
  'outfits',
  'kledingstukken',
  'kledingcollectie',
  'kledinglijn',
  'kledingmerk',
  'kledingwinkel',
  'kledingzaak',
  'kledingboetiek',
  'kledingaccessoires',
  'jassen',
  'jassen',
  'jas',
  'jacks',
  'jack',
  'vesten',
  'vest',
  'hoodies',
  'hoodie',
  'sweaters',
  'sweater',
  'truien',
  'trui',
  't-shirts',
  't-shirt',
  'tops',
  'top',
  'blouses',
  'blouse',
  'shirts',
  'shirt',
  'jeans',
  'jeans',
  'broeken',
  'broek',
  'rokken',
  'rok',
  'jurken',
  'jurk',
  'shorts',
  'short',
  'schoenen',
  'schoen',
  'sneakers',
  'sneaker',
  'sandalen',
  'sandalen',
  'laarzen',
  'laars',
  'slippers',
  'slipper',
  'regenkleding',
  'regenjas',
  'regenjassen',
  'regenjacks',
  'regenvesten',
  'regenhoodies',
  'regensweaters',
  'regentruien',
  'regent-shirts',
  'regentops',
  'regenblouses',
  'regenshirts',
  'regenjeans',
  'regenbroek',
  'regenbroeken',
  'regenrokken',
  'regenjurken',
  'regenshorts',
  'regenschoenen',
  'regensneakers',
  'regensandalen',
  'regenlaarzen',
  'regenslippers',
  'accessoires',
  'accessoire',
  'sieraden',
  'sieraad',
  'tassen',
  'tas',
  'portemonnees',
  'portemonnee',
  'riemen',
  'riem',
  'hoeden',
  'hoed',
  'sjaals',
  'sjaal',
  'handschoenen',
  'handschoen',
  'mutsen',
  'muts',
  'sokken',
  'socken',
  '/p/',
  '/c/',
  'account',
  'account',
  'login',
  'inloggen',
  'registreren',
  'aanmelden',
  'aanmelden',
  'registreer',
  'registreer',
  'wachtwoord',
  'wachtwoord vergeten',
  'wachtwoord resetten',
  'wachtwoord herstellen',
  'cart',
  'winkelwagen',
  'winkelmandje',
  'afrekenen',
  'checkout',
  'bestellen',
  'bestel',
  'bestelling',
  'order',
  'orders',
  'orderstatus',
  'track-and-trace',
  'volg-je-bestelling',
  'klantenservice',
  'contact',
  'help',
  'faq',
  'veelgestelde vragen',
  '.jpg',
  '.jpeg',
  '.png',
  '.gif',
  '.svg',
  '.webp',
  '.pdf',
  '.doc',
  '.docx',
  '.xls',
  '.xlsx',
  '.zip',
  '.tar',
  '.gz',
  '.rar',
];

export default excludeKeywords;
